"""
Output formatting for the travel itinerary agent.
Generates structured output (JSON + Markdown report).
"""
import json
from pathlib import Path
from typing import Dict, Any
from agent.state import TravelState
from datetime import datetime


def format_itinerary_markdown(state: TravelState) -> str:
    """
    Format the final itinerary as a readable Markdown report.
    
    Args:
        state: Final state after all processing steps
    
    Returns:
        Markdown formatted itinerary
    """
    
    if not state.itinerary:
        return "# Travel Itinerary\n\nNo itinerary generated. Check errors below.\n\n**Errors:**\n" + "\n".join(f"- {e}" for e in state.errors)
    
    itin = state.itinerary
    markdown_lines = []
    
    # Title
    markdown_lines.append(f"# Pathfinder Route: {itin.get('destination', 'Unknown')}")
    markdown_lines.append(f"**Generated by Pathfinder:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    
    # Trip overview
    markdown_lines.append("## Trip Overview")
    markdown_lines.append(f"- **Destination:** {itin.get('destination', 'N/A')}")
    markdown_lines.append(f"- **Duration:** {state.preferences.get('num_days', 'N/A')} days")
    markdown_lines.append(f"- **Budget:** {state.preferences.get('budget_category', 'N/A').title()}")
    markdown_lines.append(f"- **Group:** {state.preferences.get('traveling_with', 'N/A')}")
    markdown_lines.append(f"- **Estimated Total Cost:** {itin.get('total_estimated_cost', 'N/A')}\n")
    
    # Daily schedules
    if "daily_itineraries" in itin and itin["daily_itineraries"]:
        markdown_lines.append("## Day-by-Day Itinerary\n")
        
        for day_plan in itin["daily_itineraries"]:
            day_num = day_plan.get("day", "?")
            date_str = day_plan.get("date", "N/A")
            weather = day_plan.get("weather", "N/A")
            daily_budget = day_plan.get("daily_budget_estimate", "N/A")
            
            markdown_lines.append(f"### Day {day_num} - {date_str}")
            markdown_lines.append(f"**Weather:** {weather} | **Budget:** {daily_budget}\n")
            
            # Schedule
            schedule = day_plan.get("schedule", [])
            if schedule:
                markdown_lines.append("| Time | Activity | Duration | Notes |")
                markdown_lines.append("|------|----------|----------|-------|")
                for item in schedule:
                    time = item.get("time", "N/A")
                    activity = item.get("activity", "N/A")
                    duration = item.get("duration", "N/A")
                    notes = item.get("notes", "N/A")
                    markdown_lines.append(f"| {time} | {activity} | {duration} | {notes} |")
            
            # Daily tips
            tips = day_plan.get("tips", "")
            if tips:
                markdown_lines.append(f"\n**Tips:** {tips}\n")
            
            markdown_lines.append("")
    
    # Packing suggestions
    if "packing_suggestions" in itin and itin["packing_suggestions"]:
        markdown_lines.append("## Packing Suggestions\n")
        for item in itin["packing_suggestions"]:
            markdown_lines.append(f"- {item}")
        markdown_lines.append("")
    
    # Final notes
    if "final_notes" in itin and itin["final_notes"]:
        markdown_lines.append("## Final Notes\n")
        markdown_lines.append(itin["final_notes"])
        markdown_lines.append("")
    
    # Errors
    if state.errors:
        markdown_lines.append("## Processing Notes\n")
        markdown_lines.append("The following issues were encountered during processing:\n")
        for error in state.errors:
            markdown_lines.append(f"- {error}")
        markdown_lines.append("")
    
    return "\n".join(markdown_lines)


def save_output(state: TravelState, output_dir: Path = None) -> Dict[str, Path]:
    """
    Save the itinerary in multiple formats (JSON and Markdown).
    
    Args:
        state: Final agent state
        output_dir: Directory to save output (defaults to ./output)
    
    Returns:
        Dictionary with paths to saved files
    """
    
    if output_dir is None:
        output_dir = Path("output")
    
    output_dir.mkdir(exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    destination = state.preferences.get("destination", "travel").replace(" ", "_").lower()
    
    # Save JSON
    json_file = output_dir / f"itinerary_{destination}_{timestamp}.json"
    with open(json_file, "w", encoding="utf-8") as f:
        output_data = {
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "destination": destination,
            },
            "preferences": state.preferences,
            "weather_data": state.weather_data,
            "attractions": state.attractions_data,
            "matched_activities": state.matched_activities,
            "itinerary": state.itinerary,
            "errors": state.errors
        }
        json.dump(output_data, f, indent=2)
    
    # Save Markdown
    markdown_file = output_dir / f"itinerary_{destination}_{timestamp}.md"
    with open(markdown_file, "w", encoding="utf-8") as f:
        f.write(format_itinerary_markdown(state))
    
    return {
        "json": json_file,
        "markdown": markdown_file
    }


def print_summary(state: TravelState):
    """Print a summary of the agent's processing."""
    print("\n" + "="*60)
    print(state.summary())
    print("="*60 + "\n")
    
    if state.itinerary:
        print(" Travel generated successfully!")
        print(f"  Destination: {state.itinerary.get('destination', 'N/A')}")
        print(f"  Total cost estimate: {state.itinerary.get('total_estimated_cost', 'N/A')}")
    else:
        print("✗ Failed to generate itinerary")
    
    if state.errors:
        print(f"\nWarnings ({len(state.errors)}):")
        for error in state.errors:
            print(f"  - {error}")
